export const HOME_VIDEOS_SUCCESS: string = 'HOME_VIDEOS_SUCCESS';
export const HOME_VIDEOS_FAIL: string = 'HOME_VIDEOS_FAIL';
export const HOME_VIDEOS_REQUEST: string = 'HOME_VIDEOS_REQUEST';

export const SELECTED_VIDEO_REQUEST: string = 'SELECTED_VIDEO_REQUEST';
export const SELECTED_VIDEO_SUCCESS: string = 'SELECTED_VIDEO_SUCCESS';
export const SELECTED_VIDEO_FAIL: string = 'SELECTED_VIDEO_FAIL';

export const RELATED_VIDEO_REQUEST: string = 'RELATED_VIDEO_REQUEST';
export const RELATED_VIDEO_SUCCESS: string = 'RELATED_VIDEO_SUCCESS';
export const RELATED_VIDEO_FAIL: string = 'RELATED_VIDEO_FAIL';

export const SEARCHED_VIDEO_REQUEST: string = 'SEARCHED_VIDEO_REQUEST';
export const SEARCHED_VIDEO_SUCCESS: string = 'SEARCHED_VIDEO_SUCCESS';
export const SEARCHED_VIDEO_FAIL: string = 'SEARCHED_VIDEO_FAIL';

export const VIDEO_DETAILS_REQUEST: string = 'VIDEO_DETAILS_REQUEST';
export const VIDEO_DETAILS_SUCCESS: string = 'VIDEO_DETAILS_SUCCESS';
export const VIDEO_DETAILS_FAIL: string = 'VIDEO_DETAILS_FAIL';
